# Generated by Django 5.2.1 on 2025-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
