# Generated by Django 5.2.1 on 2025-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_alter_customuser_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ИНН'),
        ),
    ]
