# Generated by Django 5.2.1 on 2025-05-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoService', '0004_remove_service_how_long'),
        ('userManager', '0004_schedulerecord_schedulework'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services_record', to='autoService.service', verbose_name='Услуга'),
            preserve_default=False,
        ),
    ]
