# Generated by Django 5.2.1 on 2025-06-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoService', '0004_remove_service_how_long'),
        ('userManager', '0006_schedulerecord_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='auto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='autoService.auto', verbose_name='авто'),
            preserve_default=False,
        ),
    ]
