# Generated by Django 5.2.1 on 2025-06-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0007_schedulerecord_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerecord',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
