# Generated by Django 5.2.1 on 2025-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0008_alter_schedulerecord_options_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'Принято в работу'), ('ready_for_pickup', 'Можно забирать'), ('closed', 'Закрыт')], default='scheduled', max_length=20, verbose_name='Состояние'),
        ),
    ]
