# Generated by Django 5.2.1 on 2025-05-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'тема заявки',
                'verbose_name_plural': 'темы заявки',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время обращения')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('call', 'звонок'), ('whatsapp', 'WhatsApp')], max_length=50, verbose_name='откуда заявка')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='зарег. клиент')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voiceService.topic', verbose_name='тематика')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
