# Generated by Django 5.2.1 on 2025-06-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceService', '0002_alter_voice_source_voiceassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='voiceassignment',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Доп. инфо'),
        ),
    ]
