# Generated by Django 5.2.1 on 2025-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceService', '0003_voice_status_alter_voiceassignment_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='text',
            field=models.TextField(null=True, verbose_name='текст обращения'),
        ),
    ]
