# Generated by Django 5.2.1 on 2025-05-12 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoService', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='auto',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='autoService.mark', verbose_name='марка авто'),
        ),
        migrations.AddField(
            model_name='modelauto',
            name='model_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_auto', to='autoService.mark', verbose_name='модель'),
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='autoService.modelauto', verbose_name='модель авто'),
        ),
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoService.groupservice', verbose_name='группа'),
        ),
        migrations.AddField(
            model_name='priceservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='autoService.service', verbose_name='услуга'),
        ),
    ]
