# Generated by Django 5.2.1 on 2025-05-14 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoService', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Мастера'),
        ),
    ]
