# Generated by Django 5.2.1 on 2025-05-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoService', '0003_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='how_long',
        ),
    ]
