# Generated by Django 5.2.1 on 2025-06-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoService', '0004_remove_service_how_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelauto',
            name='body_type',
            field=models.CharField(choices=[('light', 'легкий'), ('medium', 'средний'), ('hard', 'тяжелый')], default='light', max_length=20, verbose_name='тип кузова'),
        ),
    ]
